# Generated by Django 2.2 on 2020-09-27 14:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200927_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(null=True, upload_to='student_profile/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(null=True, upload_to='student_resume/', validators=[accounts.models.resume_validator]),
        ),
    ]
