# Generated by Django 3.1.1 on 2020-09-30 19:48

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20200927_1740'),
        ('accounts', '0005_auto_20200930_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='education.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resume/', validators=[accounts.models.resume_validator]),
        ),
    ]
