# Generated by Django 2.2 on 2020-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(upload_to='course_files/'),
        ),
    ]
