# Generated by Django 2.2 on 2020-10-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20200927_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
